### PR TITLE
Package and serve binaries for all RHEL architectures

### PR DESCRIPTION
**Pull request by yselkowitz**
Filing relevant parts to master based on feedback in #411

### CODE REVIEW

**Comment by warrenvw** [comment]
After discussion with Yaakov, it's time to merge this PR. There are no known issues which prevent the client from building for all architectures, even if serving, eventing, etc. are only built for x86_64.

**Comment by rhuss** [comment]
/lgtm
/approve

Thanks ! Let's get that in for 1.13 ....

**Pull request merged**
