### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by dsimansk** [comment]
/retest
```
     result_collector.go:75: ERROR: Error: conversion webhook for sources.knative.dev/v1alpha2, Kind=PingSource failed: Post https://eventing-webhook.knative-eventing.svc:443/?timeout=30s: x509: certificate signed by unknown authority 
```

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
