### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by rhuss** [comment]
@navidshaikh I guess the PR needs to be rebased on master first (as this is still the release-next-ci branch)

I suggest just to merge and wait for tomorrow nights PR ?

**Comment by navidshaikh** [comment]
@rhuss : 
> I guess the PR needs to be rebased on master first (as this is still the release-next-ci branch)

Yup.

> I suggest just to merge and wait for tomorrow nights PR ?

We can run https://github.com/openshift/knative-client/blob/master/openshift/release/update-to-head.sh to update `release-next` and `release-next-ci` branches to update same PR, I just ran same above.

**Comment by navidshaikh** [comment]
Failure of tests complains
```
🔥 No license header found in:
   ./openshift/olm/knative-serving.catalogsource.yaml
```

**Comment by alanfx** [comment]
Hm, not sure why the webhook didn't merge this PR. I'll take a look

**Pull request merged**
