### PR TITLE
Move catalogsource to the same namespace with subscription

### PR DESCRIPTION
**Pull request by navidshaikh**
as done in https://github.com/openshift/knative-serving/pull/206

 All credits to @nak3

### CODE REVIEW

**Comment by nak3** [comment]
@navidshaikh It is not possible to trigger to the test with this change? This looks good to me, but if we can verify it by running test before merge, it would be great.

**Comment by rhuss** [comment]
Yes, I wonder, too how we can run CI for PR. At the moment no single test is performed at all.

**Comment by navidshaikh** [comment]
@nak3 @rhuss : I've opened https://github.com/openshift/knative-client/pull/47 to test this PR, stacked commit on top of release-next branch (which would be the case when this PR merged).

**Comment by nak3** [comment]
@navidshaikh Thank you. https://github.com/openshift/knative-client/pull/47 is failing but at least serving-operator successfully deployed serving so this PR is LGTM. Can you solve the conflicted files?

**Comment by navidshaikh** [comment]
@nak3 : Yup, tested this change in different PR #48 and its went well, I think we're good.
/cc @markusthoemmes

**Comment by navidshaikh** [comment]
Thanks a lot @nak3 for the fix and review!

**Pull request merged**
