### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by navidshaikh**

### CODE REVIEW

**Comment by navidshaikh** [comment]
/hold

Test PR.

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Comment by navidshaikh** [comment]
@alanfx : FYI - hold couldn't prevent the PR from merging 

Also this PR was raised after merge of https://github.com/openshift/release/pull/6726, which sets up OCP 4.3 setup, but the above job says OCP 4.2. @mgencur any idea if I missed something here ?

**Comment by mgencur** [comment]
@navidshaikh the ci-operator confmaps on the other PR were updated just two hours ago. I think this job with tests was triggered before that so it was still using OCP 4.2. A new run should already be using OCP 4.3. IMO

**Comment by navidshaikh** [comment]
@mgencur : Just reconfirmed the PR order, this was created 3 minutes post the release PR merged. I've opened https://github.com/openshift/knative-client/pull/235 and I could see the job picked up the latest changes of config map, now running OCP 4.3. Looks like the sync took 3+ mins, nvm. Thank you!

**Pull request merged**
