### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

```
    cli.go:70: ERROR: timeout: service 'svc6' not ready after 600 seconds
```

**Comment by rhuss** [comment]
This is an issue with eventing 0.13.0 removing some sources, but our tests still have asserts for these.

**Comment by rhuss** [comment]
I jump now on updating out dependencies to 0.13.0 and fixing that issue as part of this.

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
