### PR TITLE
Remove tech-preview from LABELs in Dockerfiles

### PR DESCRIPTION
**Pull request by warrenvw**
Preparing for first GA release.

### CODE REVIEW

**Comment by navidshaikh** [comment]
This PR is against `release-v0.13.1` branch, we've cut kn `v0.13.1` release already using it.
We're doing v0.13.2 in next week. 
These changes should land in master and already have https://github.com/openshift/knative-client/pull/325. The changes will be propagated to `release-v0.13.2` branch part of 'Update openshift specific files'.

/hold

**Comment by warrenvw** [comment]
I was dropping it on the release-v0.13.1 branch so that we could add kn client to the advisory today with the understanding that we would update the image appropriately prior to release.

**Comment by warrenvw** [comment]
But let's go ahead and close this PR if it doesn't make sense anymore. :)

**Pull request closed without merging**
