### PR TITLE
[1.1] kn event tests

### PR DESCRIPTION
**Pull request by cardil**
Tests moved out of #1007

### CODE REVIEW

**Comment by dsimansk** [comment]
PTAL 
https://github.com/openshift/knative-client/pull/1016/commits/f60f35a0297c7f1b94d059653a773eceab1ab73e

**Comment by cardil** [comment]
We can merge this as it is or wait for https://github.com/openshift-knative/kn-plugin-event/pull/141 to be merged and cherrypicked on top of 1.1 images.

/cc @dsimansk

**Pull request merged**
