### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by navidshaikh** [comment]
/retest

This started coming again, I remember seeing someone complain about it upstream as well. @rhuss 

        ┃  11.374s Ingress has not yet been reconciled.

**Comment by navidshaikh** [comment]
/retest

    result_collector.go:75: ERROR: Error: RevisionFailed: Revision "hello-jmfhy-1" failed with message: Unable to fetch image "registry.build01.ci.openshift.org/ci-op-6w2viv47/stable:knative-client-test-helloworld": failed to resolve image to digest: failed to initialize authentication: serviceaccounts "default" not found.


controller is in action before the SA is setup ? :thinking:

**Comment by navidshaikh** [comment]
/retest

          🔥 Error: timeout: service 'echo0' not ready after 600 seconds

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
