### PR TITLE
Update KOURIER_GATEWAY_NAMESPACE

### PR DESCRIPTION
**Pull request by navidshaikh**
see https://github.com/openshift/knative-serving/pull/535/

### CODE REVIEW

**Comment by dsimansk** [comment]
@navidshaikh there're `sed` 2 changes in the original operator PR. Should we get both also?
```
  # Add env variable manually until operator implments it. See SRVKS-610
  sed -i -e 's/value: "kourier-system"/value: "knative-serving-ingress"/g'  third_party/kourier-latest/kourier.yaml
  sed -i -e 's/kourier-control.knative-serving/kourier-control.knative-serving-ingress/g'  third_party/kourier-latest/kourier.yaml
```

**Comment by navidshaikh** [comment]
@dsimansk : yup, updated the PR.

**Comment by navidshaikh** [comment]
/hold

@dsimansk would need lgtm on https://github.com/openshift/knative-client/pull/445 (against master) once CI in this PR is through.

**Comment by dsimansk** [comment]
Sure, sorry I haven't realized that's not master.

**Pull request closed without merging**
