### PR TITLE
Add all RHEL architectures

### PR DESCRIPTION
**Pull request by yselkowitz**
The "build and release" commit is relevant to upstream, the "package and serve" commit should be midstream-specific.  Let me know if I need to handle the former differently.

### CODE REVIEW

**Comment by navidshaikh** [comment]
> The changes in first commit 'Build and release' should ideally go upstream, files changed in that commit (hack/build.sh, hack/release.sh) are synced from upstream,
and its better done upstream than carry any patch for them.

@yselkowitz : @rhuss suggests to hold on raising the additional arch build/release PR upstream, as we'd comply to support them which is more feasible downstream than upstream.

**Comment by yselkowitz** [comment]
I have filed PRs for master and release-next here, along with in the operator to add the links.  The kn-cli-artifacts Dockerfile does require a change as you mention, but it appears that needs to be coordinated downstream.  Where is the mirror.openshift.com sync script hosted?

**Comment by navidshaikh** [comment]
> Where is the mirror.openshift.com sync script hosted?

https://github.com/openshift/aos-cd-jobs/blob/master/build-scripts/rcm-guest/publish-kn-binary.sh

The input URL for this script to download the binaries are given by RCM after signing binaries for macOS and Windows. RCM extracts the `-redistributable` RPM and sign the mentioned platform binaries and copy over other binaries at export location. 
The sync script in its current form will be used by ART team for syncing the binaries for release which is on QA now.
We'll first need to co-ordinate with RCM about export location structure and notify about the change coming, I will copy you on the ticket.

**Comment by yselkowitz** [comment]
Since this won't make 0.14.0, closing this PR in favour of the others since flied.

**Pull request closed without merging**
