### PR TITLE
[1.1] Embed kn-event

### PR DESCRIPTION
**Pull request by cardil**
Embedding kn-event at [openshift-knative/kn-plugin-event@`release-1.1`](https://github.com/openshift-knative/kn-plugin-event/tree/release-1.1) (pinned at https://github.com/openshift-knative/kn-plugin-event/commit/2c22e325c97715eeabe866eea1be9bbf44737f3d).

~Running e2e tests of kn-event.~ Tests execution will be extracted to follow-up PR to proceed further.

### CODE REVIEW

**Comment by cardil** [comment]
This is odd. I tested this on local CRC, and it worked just fine. Debugging needed.

/hold

**Comment by cardil** [comment]
Looking at `wathola-forwarder` logs (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_knative-client/1007/pull-ci-openshift-knative-client-release-v1.1.0-e2e-aws-ocp-410/1512059273134215168/artifacts/e2e-aws-ocp-410/gather-extra/artifacts/pods/test-vhflgeze_sink-beenmaby-ksvc-00001-deployment-8b8cf747c-75t9w_user-container.log) it looks like the container expect to look at `/root/.config/wathola/config.toml` for config file, but we are setting it to `''`:

https://github.com/cardil/knative-client/blob/e686bb8b3b2b283eba8bfd32d1278ccc7dba2ef0/openshift/e2e-common.sh#L132

We are setting it to `''` (empty string) because on OpenShift, the container should be executed with limited UID|GID (different from `root (uid:0, gid:0)`). That was forcing the user home to be unset, and in turn the config file is expected to be in `/.config/wathola/config.toml`.

This issue has already been raised as:

- https://bugzilla.redhat.com/show_bug.cgi?id=1894063
- https://github.com/knative/eventing/issues/4444
- https://github.com/knative/eventing/pull/4445
- https://github.com/openshift/knative-eventing/pull/939

What's strange for me is the current code, works on my local clusters :tm: (both CRC, and AWS-backed).

I have no idea, why in this CI the OpenShift seams to run the test pod as real `root (uid:0, gid:0)` user :confused:.

**Comment by cardil** [comment]
/unhold

Tests have been moved to separate follow-up PR #1015

**Review by dsimansk — APPROVED** [review]

**Comment by cardil** [comment]
@dsimansk still missing lgtm label

**Pull request merged**
