### PR TITLE
Add all RHEL architectures

### PR DESCRIPTION
**Pull request by yselkowitz**
Filing to release-next based on feedback in #411

### CODE REVIEW

**Comment by yselkowitz** [comment]
v0.17.3 backport is #524

**Comment by yselkowitz** [comment]
Submitted first patch upstream as https://github.com/knative/client/pull/1153, second patch is openshift-specific.

**Comment by navidshaikh** [comment]
/retest

   VpcLimitExceeded

**Comment by yselkowitz** [comment]
Closing in favour of #413

**Pull request closed without merging**
