### PR TITLE
[release-v1.2.0] Add kn-plugin-source-kafka v1.2.0

### PR DESCRIPTION
**Pull request by dsimansk**
per title

/cc @rhuss

### CODE REVIEW

**Comment by dsimansk** [comment]
> To get the context right: This is about adding the plugins that we directly import from upstream, while plugins that have a midstream counterpart are added somewhere else ? (asking because I only see kn-source-kafka in this PR)

I was planning to add them one by one. To keep the context separation. For event plugin there're some E2E tests as well to verify those work fine etc. And func will be added once we have upstream tag, hopefully later today.

**Comment by rhuss** [comment]
I see, thanks !

/approve
/lgtm

**Pull request merged**
