### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by navidshaikh** [comment]
/test images

error: failed to load configuration: Response from configresolver != 200

**Comment by navidshaikh** [comment]
/test e2e-aws-ocp-42

Process did not finish before 4h0m0s timeout

**Comment by navidshaikh** [comment]
/test e2e-aws-ocp-42

error: failed to load configuration: Response from configresolver != 200

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
