### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by navidshaikh** [comment]
The referenced commits in this PR are tested, updated other sync PR accordingly. Closing!

**Comment by navidshaikh** [comment]
> The referenced commits in this PR are tested, updated other sync PR accordingly. Closing!

doh! That comment was for the other PR https://github.com/openshift/knative-client/pull/48

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
