### PR TITLE
[release-v0.19.1] Fix for serviceaccounts "default" not found flaky issue

### PR DESCRIPTION
**Pull request by pratham-m**
This PR intends to fix **serviceaccount "default" not found** flaky issue which is a race condition observed on some OCP4.x platforms.

### CODE REVIEW

**Comment by dsimansk** [comment]
@rhuss could you please approve, I'm not an approver long enough to be present in release-v0.19.1 branch. :)

**Comment by alanfx** [comment]
@rhuss yes, can you take a look at this one? I am on the right approver list, however this PR isn't getting merged even though it is `approved` and `lgtm` labels?

**Pull request merged**
